//! Parse and generate workspace/auth.env.local.

use rand::RngCore;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub fn default_auth_env_path() -> PathBuf {
    std::env::var("OPENFDD_WORKSPACE")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("workspace"))
        .join("auth.env.local")
}

pub fn parse_env_file(content: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            out.insert(k.trim().to_string(), v.trim().to_string());
        }
    }
    out
}

pub fn load_env_file(path: &Path) -> std::io::Result<HashMap<String, String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(parse_env_file(&text)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(HashMap::new()),
        Err(e) => Err(e),
    }
}

pub fn apply_env_file(path: &Path) {
    if let Ok(map) = load_env_file(path) {
        for (k, v) in map {
            if std::env::var(&k).is_err() {
                std::env::set_var(k, v);
            }
        }
    }
}

fn random_secret_hex(bytes: usize) -> String {
    let mut buf = vec![0_u8; bytes];
    rand::thread_rng().fill_bytes(&mut buf);
    hex::encode(buf)
}

fn random_password() -> String {
    const CHARSET: &[u8] = b"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#%^*_-";
    let mut rng = rand::thread_rng();
    (0..28)
        .map(|_| {
            let idx = (rng.next_u32() as usize) % CHARSET.len();
            CHARSET[idx] as char
        })
        .collect()
}

pub struct GenerateOptions {
    pub path: PathBuf,
    pub force: bool,
    pub show_secrets: bool,
}

pub struct GenerateResult {
    pub created: bool,
    pub path: PathBuf,
    pub contents: String,
}

pub fn generate_auth_env(opts: &GenerateOptions) -> std::io::Result<GenerateResult> {
    if opts.path.exists() && !opts.force {
        let contents = fs::read_to_string(&opts.path)?;
        return Ok(GenerateResult {
            created: false,
            path: opts.path.clone(),
            contents,
        });
    }

    if let Some(parent) = opts.path.parent() {
        fs::create_dir_all(parent)?;
    }

    let secret = random_secret_hex(32);
    let operator_pw = random_password();
    let integrator_pw = random_password();
    let agent_pw = random_password();

    let contents = format!(
        "# Open-FDD edge auth — generated by openfdd_edge auth init\n\
         # chmod 600 recommended. Never commit this file.\n\
         OFDD_AUTH_REQUIRED=true\n\
         OFDD_AUTH_SECRET={secret}\n\
         OFDD_OPERATOR_USER=operator\n\
         OFDD_OPERATOR_PASSWORD={operator_pw}\n\
         OFDD_INTEGRATOR_USER=integrator\n\
         OFDD_INTEGRATOR_PASSWORD={integrator_pw}\n\
         OFDD_AGENT_USER=agent\n\
         OFDD_AGENT_PASSWORD={agent_pw}\n\
         OFDD_JWT_TTL_SECONDS=28800\n\
         OFDD_COOKIE_SECURE=false\n"
    );

    fs::write(&opts.path, &contents)?;
    chmod_600_unix(&opts.path);

    Ok(GenerateResult {
        created: true,
        path: opts.path.clone(),
        contents,
    })
}

pub fn chmod_600_unix(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = fs::metadata(path) {
            let mut perms = meta.permissions();
            perms.set_mode(0o600);
            let _ = fs::set_permissions(path, perms);
        }
    }
}

pub fn redact_env_line(key: &str, value: &str) -> String {
    if key.contains("SECRET") || key.contains("PASSWORD") || key.contains("TOKEN") {
        format!("{key}=***REDACTED***")
    } else {
        format!("{key}={value}")
    }
}

pub fn print_env_summary(contents: &str, show_secrets: bool) {
    for line in contents.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            if show_secrets {
                println!("{k}={v}");
            } else {
                println!("{}", redact_env_line(k, v));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_auth_path() -> PathBuf {
        let n = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("openfdd-auth-{n}.env"))
    }

    #[test]
    fn generated_file_contains_all_users() {
        let path = temp_auth_path();
        let _ = fs::remove_file(&path);
        let result = generate_auth_env(&GenerateOptions {
            path: path.clone(),
            force: true,
            show_secrets: false,
        })
        .unwrap();
        assert!(result.created);
        assert!(result.contents.contains("OFDD_OPERATOR_USER=operator"));
        assert!(result.contents.contains("OFDD_INTEGRATOR_USER=integrator"));
        assert!(result.contents.contains("OFDD_AGENT_USER=agent"));
        let _ = fs::remove_file(path);
    }

    #[test]
    fn existing_file_preserved_without_force() {
        let path = temp_auth_path();
        fs::write(&path, "OFDD_AUTH_SECRET=keep-me\n").unwrap();
        let result = generate_auth_env(&GenerateOptions {
            path: path.clone(),
            force: false,
            show_secrets: false,
        })
        .unwrap();
        assert!(!result.created);
        assert!(result.contents.contains("keep-me"));
        let _ = fs::remove_file(path);
    }
}
