<#
Rotate-OpenFddAuthEnv-v3.4.ps1

Generate a fresh local Open-FDD auth.env.local file beside these PowerShell scripts by default.
Use this after a credential exposure or before a cleaner test run.

This script does not print generated secrets to the console.
It backs up an existing file by default.
#>

param(
    [string]$OutFile = "",
    [switch]$NoBackup,
    [int]$SecretBytes = 48,
    [int]$PasswordBytes = 36
)

$ErrorActionPreference = "Stop"

function New-Base64UrlSecret {
    param([int]$Bytes = 32)
    $Buffer = New-Object byte[] $Bytes

    # Compatible with Windows PowerShell 5.1 / older .NET Framework.
    # RandomNumberGenerator::Fill exists only on newer .NET versions.
    $Rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $Rng.GetBytes($Buffer)
    }
    finally {
        if ($null -ne $Rng) { $Rng.Dispose() }
    }

    return ([Convert]::ToBase64String($Buffer).TrimEnd('=') -replace '\+','-' -replace '/','_')
}

$ScriptDir = if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) { (Get-Location).Path } else { $PSScriptRoot }
if ([string]::IsNullOrWhiteSpace($OutFile)) { $OutFile = Join-Path $ScriptDir "auth.env.local" }
elseif (-not [System.IO.Path]::IsPathRooted($OutFile)) { $OutFile = Join-Path $ScriptDir $OutFile }

$FullPath = $OutFile
$Dir = Split-Path -Parent $FullPath
if (-not (Test-Path $Dir)) { New-Item -ItemType Directory -Force -Path $Dir | Out-Null }

if ((Test-Path $FullPath) -and -not $NoBackup) {
    $Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $Backup = "$FullPath.bak-$Stamp"
    Copy-Item -Path $FullPath -Destination $Backup -Force
    Write-Host "Backed up existing auth env to: $Backup" -ForegroundColor Yellow
}

$Content = @"
# Open-FDD auth settings.
# Generated by Rotate-OpenFddAuthEnv-v3.4.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# WARNING: Do not commit this file. Do not paste it into chat, tickets, PRs, or logs.

OFDD_AUTH_SECRET=$(New-Base64UrlSecret -Bytes $SecretBytes)

OFDD_OPERATOR_USER=operator
OFDD_OPERATOR_PASSWORD=$(New-Base64UrlSecret -Bytes $PasswordBytes)

OFDD_INTEGRATOR_USER=integrator
OFDD_INTEGRATOR_PASSWORD=$(New-Base64UrlSecret -Bytes $PasswordBytes)

OFDD_AGENT_USER=agent
OFDD_AGENT_PASSWORD=$(New-Base64UrlSecret -Bytes $PasswordBytes)

# Recommended token lifetime for OT dashboards: 8 hours.
OFDD_AUTH_TTL_SEC=28800

# Optional: prefer password hashes for production if your Open-FDD build supports them.
# From the repo/server, run the project hash helper and replace plaintext values with *_PASSWORD_HASH values.
# Example:
#   python workspace/scripts/hash_password.py
"@

$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($FullPath, $Content, $Utf8NoBom)
Write-Host "Created fresh Open-FDD auth env: $FullPath" -ForegroundColor Green
Write-Host "Generated values were written to the file only and were not printed." -ForegroundColor Green
Write-Host "Restart/reload Open-FDD/Caddy after replacing the file so the new credentials take effect." -ForegroundColor Cyan
