"""
Default FDD energy-penalty equation catalog (engineering narratives + calc_type mapping).

Seeded per-site as disabled EnergyCalculation rows (external_id prefix ``penalty_default_``).
Open-Meteo and utility rates remain on ``ofdd:platform_config`` / site config — see configuration docs.
"""

from __future__ import annotations

from typing import Any

# --- 18 default penalty narratives (difficulty 1 = easiest) -----------------

PENALTY_CATALOG: list[dict[str, Any]] = [
    {
        "seq": 1,
        "layer": "general",
        "difficulty": 1,
        "name": "Out-of-schedule operation",
        "fdd_trigger": "equipOn == true while unoccupied schedule active",
        "math_summary": r"E_waste = \sum (P \cdot \Delta t)",
        "calc_type": "runtime_electric_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 1,
            "kw": 0,
            "hours_fault": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 2,
        "layer": "general",
        "difficulty": 1,
        "name": "HOA in Hand (vs optimal auto speed)",
        "fdd_trigger": "Override to 100% while PID would command lower speed",
        "math_summary": r"\Delta kW \approx kW_{max} (1 - (S_{auto}/S_{max})^3)",
        "calc_type": "vfd_affinity_cube",
        "default_parameters": {
            "_penalty_catalog_seq": 2,
            "p_full_kw": 0,
            "speed_base_pct": 100,
            "speed_prop_pct": 70,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 3,
        "layer": "zone",
        "difficulty": 2,
        "name": "Zone deadband hunting / simultaneous HC",
        "fdd_trigger": "Heating and cooling setpoints too tight; rapid cycling",
        "math_summary": r"BTU/h \approx Q_{cool} + Q_{heat} (sensible streams)",
        "calc_type": "zone_simultaneous_sensible",
        "default_parameters": {
            "_penalty_catalog_seq": 3,
            "cfm": 0,
            "q_cool_btu_h": 0,
            "q_heat_btu_h": 0,
            "hours": 0,
            "cop": 3.5,
            "heating_efficiency": 0.8,
            "electric_rate_per_kwh": 0.12,
            "therm_rate_usd": 1.0,
            "assign_cooling_to": "electric",
        },
    },
    {
        "seq": 4,
        "layer": "zone",
        "difficulty": 2,
        "name": "VAV minimum flow too high (reheat penalty)",
        "fdd_trigger": "Unoccupied or satisfied but min CFM above design / 62.1",
        "math_summary": r"Q \approx 1.08 \cdot (CFM_{act} - CFM_{min}) \cdot (T_{zone} - T_{supply})",
        "calc_type": "vav_min_flow_reheat",
        "default_parameters": {
            "_penalty_catalog_seq": 4,
            "cfm_excess": 0,
            "delta_t_f": 0,
            "hours": 0,
            "heating_efficiency": 0.8,
            "therm_rate_usd": 1.0,
        },
    },
    {
        "seq": 5,
        "layer": "airside",
        "difficulty": 2,
        "name": "AHU SAT not resetting (GL36-style)",
        "fdd_trigger": "No cooling requests but SAT stuck at minimum",
        "math_summary": r"Q \approx 1.08 \cdot CFM \cdot (SAT_{opt} - SAT_{act})",
        "calc_type": "ahu_sat_sensible_waste",
        "default_parameters": {
            "_penalty_catalog_seq": 5,
            "cfm": 0,
            "sat_opt_f": 65,
            "sat_actual_f": 55,
            "hours": 0,
            "cop": 3.5,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 6,
        "layer": "airside",
        "difficulty": 2,
        "name": "Duct static SP not resetting",
        "fdd_trigger": "No VAV requests; static at max",
        "math_summary": r"\Delta kW \approx kW_{act} (1 - (P_{opt}/P_{act})^{1.5})",
        "calc_type": "pressure_ratio_motor_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 6,
            "kw_actual": 0,
            "p_actual": 3.0,
            "p_opt": 1.5,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 7,
        "layer": "airside",
        "difficulty": 3,
        "name": "Simultaneous HC — leaking heating valve",
        "fdd_trigger": "Cooling active but \u0394T across HW coil when valve should be closed",
        "math_summary": r"Q \approx 1.08 \cdot CFM \cdot \Delta T_{coil}",
        "calc_type": "sensible_coil_leak_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 7,
            "cfm": 0,
            "delta_t_coil_f": 0,
            "hours": 0,
            "cop": 3.5,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 8,
        "layer": "airside",
        "difficulty": 3,
        "name": "Dirty filter / fouled coil (extra fan kW)",
        "fdd_trigger": "\u0394P across filter/coil >> baseline",
        "math_summary": r"kW \approx CFM \cdot \Delta P_{excess} / (6356 \eta_f \eta_m) \cdot 0.746",
        "calc_type": "fan_filter_dp_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 8,
            "cfm": 0,
            "delta_p_excess_inwc": 0,
            "eta_fan": 0.65,
            "eta_motor": 0.92,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 9,
        "layer": "airside",
        "difficulty": 3,
        "name": "Missed air-side economizer",
        "fdd_trigger": "Favorable OA; OA damper at minimum with cooling load",
        "math_summary": r"Q_{missed} \approx 1.08 \cdot CFM \cdot (T_{return} - T_{outside})",
        "calc_type": "missed_economizer_cooling",
        "default_parameters": {
            "_penalty_catalog_seq": 9,
            "cfm": 0,
            "t_return_f": 75,
            "t_outside_f": 55,
            "hours": 0,
            "cop": 3.5,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 10,
        "layer": "airside",
        "difficulty": 4,
        "name": "Energy recovery wheel / DOAS deficit (proxy)",
        "fdd_trigger": "Extreme OA; wheel bypassed or failed",
        "math_summary": r"Q \approx 4.5 \cdot CFM_{OA} \cdot \Delta h (enthalpy proxy)",
        "calc_type": "enthalpy_wheel_proxy",
        "default_parameters": {
            "_penalty_catalog_seq": 10,
            "cfm_oa": 0,
            "delta_h_ft_lb_per_lb": 0,
            "hours": 0,
            "cop": 3.5,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 11,
        "layer": "airside",
        "difficulty": 4,
        "name": "Overcool AHU + downstream VAV reheat",
        "fdd_trigger": "Low SAT; many zones in reheat",
        "math_summary": r"Q \approx 1.08 \cdot CFM \cdot (T_{ideal SAT} - T_{actual SAT})",
        "calc_type": "ahu_sat_sensible_waste",
        "default_parameters": {
            "_penalty_catalog_seq": 11,
            "cfm": 0,
            "sat_opt_f": 65,
            "sat_actual_f": 55,
            "hours": 0,
            "cop": 3.5,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 12,
        "layer": "plant",
        "difficulty": 3,
        "name": "Chiller on at no load / missed waterside FC",
        "fdd_trigger": "Chiller ON; OA cold or all valves closed",
        "math_summary": r"E = \sum (kW_{min,chiller} + kW_{pumps}) \Delta t",
        "calc_type": "plant_minimum_stack_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 12,
            "kw_stack": 0,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 13,
        "layer": "plant",
        "difficulty": 3,
        "name": "Boiler / HW in deadband or no-load",
        "fdd_trigger": "HW plant ON; OAT in deadband or no reset requests",
        "math_summary": r"Gas + pump kWh proxy",
        "calc_type": "boiler_standby_mix",
        "default_parameters": {
            "_penalty_catalog_seq": 13,
            "kw_hw_pump": 0,
            "boiler_min_btu_h": 0,
            "hours": 0,
            "boiler_efficiency": 0.8,
            "therm_rate_usd": 1.0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 14,
        "layer": "plant",
        "difficulty": 3,
        "name": "Equipment short cycling (financial proxy)",
        "fdd_trigger": "Starts per hour > manufacturer guidance",
        "math_summary": r"Penalty \approx (N - N_{allow}) C_{wear} + 0.1 E",
        "calc_type": "short_cycle_financial",
        "default_parameters": {
            "_penalty_catalog_seq": 14,
            "starts_per_hour": 0,
            "allowed_starts_per_hour": 6,
            "cost_wear_usd_per_start": 25,
            "kwh_in_period": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 15,
        "layer": "plant",
        "difficulty": 3,
        "name": "CHWST not resetting",
        "fdd_trigger": "Low lift; CHWST stuck at design minimum",
        "math_summary": r"kW_{waste} \approx kW_{act} \cdot 0.015 \cdot (CHWST_{opt} - CHWST_{act})",
        "calc_type": "chwst_reset_penalty_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 15,
            "kw_actual": 0,
            "chwst_opt_f": 55,
            "chwst_actual_f": 42,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 16,
        "layer": "plant",
        "difficulty": 3,
        "name": "Pump DP setpoint not resetting",
        "fdd_trigger": "No requests; DP at max",
        "math_summary": r"\Delta kW \approx kW_{act} (1 - (DP_{opt}/DP_{act})^{1.5})",
        "calc_type": "pressure_ratio_motor_kw",
        "default_parameters": {
            "_penalty_catalog_seq": 16,
            "kw_actual": 0,
            "p_actual": 40,
            "p_opt": 20,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 17,
        "layer": "plant",
        "difficulty": 4,
        "name": "Cooling tower fan hunting / impossible setpoint",
        "fdd_trigger": "Fans 100% but CWS satisfied or setpoint below WB+approach",
        "math_summary": r"\Delta kW_{fan} from affinity vs optimal speed",
        "calc_type": "vfd_affinity_cube",
        "default_parameters": {
            "_penalty_catalog_seq": 17,
            "p_full_kw": 0,
            "speed_base_pct": 100,
            "speed_prop_pct": 60,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
    {
        "seq": 18,
        "layer": "plant",
        "difficulty": 4,
        "name": "Degraded chiller capacity (COP gap)",
        "fdd_trigger": "High kW; low \u0394T on evaporator vs design",
        "math_summary": r"kW_{waste} = Q (1/(3.412 COP_a) - 1/(3.412 COP_d))",
        "calc_type": "cop_gap_electric",
        "default_parameters": {
            "_penalty_catalog_seq": 18,
            "q_load_btu_h": 0,
            "cop_actual": 4.0,
            "cop_design": 6.0,
            "hours": 0,
            "electric_rate_per_kwh": 0.12,
        },
    },
]


def catalog_rows_for_seed() -> list[dict[str, Any]]:
    """Build insert payloads: external_id, name, description, calc_type, parameters."""
    rows: list[dict[str, Any]] = []
    for e in PENALTY_CATALOG:
        seq = e["seq"]
        ext = f"penalty_default_{seq:02d}"
        desc_parts = [
            f"[Layer: {e['layer']}, difficulty {e['difficulty']}/4]",
            f"Trigger: {e['fdd_trigger']}",
            f"Math: {e['math_summary']}",
        ]
        rows.append(
            {
                "external_id": ext,
                "name": e["name"],
                "description": "\n\n".join(desc_parts),
                "calc_type": e["calc_type"],
                "parameters": dict(e["default_parameters"]),
                "point_bindings": {},
                "enabled": False,
            }
        )
    return rows


