# Mosquitto MQTTS (listener 8883, cert auth, no anonymous)

persistence true
persistence_location /mosquitto/data/

listener 8883
protocol mqtt
allow_anonymous false
require_certificate true
use_identity_as_username true
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/server.cert.pem
keyfile /mosquitto/certs/server.key.pem
acl_file /mosquitto/config/acl

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
