#!/usr/bin/env bash
# Bootstrap local Ollama for Open-FDD operator AI chat.
#
#   ./scripts/bootstrap_ollama.sh --ram-tier 8gb              # flimsiest (TinyLlama) — 8GB lab hosts
#   ./scripts/bootstrap_ollama.sh --ram-tier 16gb --gpu auto
#   ./scripts/bootstrap_ollama.sh --ram-tier 32gb --gpu gpu
#   ./scripts/bootstrap_ollama.sh --ram-tier 64gb --pull-only
#
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RAM_TIER="${OFDD_OLLAMA_RAM_TIER:-8gb}"
GPU_MODE="${OFDD_OLLAMA_GPU_MODE:-cpu}"
PULL_ONLY=false
START_ONLY=false
USER_LOCAL=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ram-tier) RAM_TIER="$2"; shift 2 ;;
    --gpu) GPU_MODE="$2"; shift 2 ;;
    --pull-only) PULL_ONLY=true; shift ;;
    --start-only) START_ONLY=true; shift ;;
    --user-local) USER_LOCAL=true; shift ;;
    -h|--help)
      sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

case "$RAM_TIER" in
  8gb)  MODEL="tinyllama" ;;
  16gb) MODEL="llama3.2:1b" ;;
  32gb) MODEL="llama3.2:3b" ;;
  64gb) MODEL="llama3.1:8b" ;;
  *) echo "Invalid --ram-tier (use 8gb|16gb|32gb|64gb): $RAM_TIER" >&2; exit 1 ;;
esac

case "$GPU_MODE" in
  cpu)  NUM_GPU=0 ;;
  auto) NUM_GPU=-1 ;;
  gpu)  NUM_GPU=99 ;;
  *) echo "Invalid --gpu (use cpu|auto|gpu): $GPU_MODE" >&2; exit 1 ;;
esac

ENV_FILE="${ROOT}/workspace/ollama.env.local"
cat >"$ENV_FILE" <<EOF
# Generated by scripts/bootstrap_ollama.sh — loaded by run_local.sh
OFDD_AI_BACKEND=auto
OFDD_OLLAMA_RAM_TIER=${RAM_TIER}
OFDD_OLLAMA_GPU_MODE=${GPU_MODE}
OFDD_OLLAMA_NUM_GPU=${NUM_GPU}
OFDD_OLLAMA_MODEL=${MODEL}
OFDD_OLLAMA_BASE_URL=http://127.0.0.1:11434
EOF
echo "Wrote ${ENV_FILE}"

OLLAMA_DIR="${ROOT}/workspace/.local-run/ollama"
OLLAMA_BIN="ollama"

resolve_ollama_arch() {
  case "$(uname -m)" in
    x86_64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *)
      echo "Unsupported CPU architecture for Ollama bootstrap: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

install_user_local() {
  mkdir -p "$OLLAMA_DIR"
  if [[ ! -x "${OLLAMA_DIR}/bin/ollama" ]]; then
    if ! command -v zstd >/dev/null; then
      echo "zstd is required to install Ollama — install it (e.g. sudo apt install zstd) and retry." >&2
      exit 1
    fi
    local arch tmp
    arch="$(resolve_ollama_arch)"
    echo "==> Installing Ollama to ${OLLAMA_DIR} (no sudo, ${arch})…"
    tmp="${OLLAMA_DIR}/ollama.tar.zst"
    curl -fsSL -L "https://github.com/ollama/ollama/releases/latest/download/ollama-linux-${arch}.tar.zst" -o "$tmp"
    zstd -d "$tmp" -o "${OLLAMA_DIR}/ollama.tar"
    tar -xf "${OLLAMA_DIR}/ollama.tar" -C "$OLLAMA_DIR"
    rm -f "$tmp" "${OLLAMA_DIR}/ollama.tar"
  fi
  OLLAMA_BIN="${OLLAMA_DIR}/bin/ollama"
  export PATH="${OLLAMA_DIR}/bin:${PATH}"
}

if [[ "$START_ONLY" == true ]]; then
  :
elif [[ "$USER_LOCAL" == true ]]; then
  install_user_local
elif [[ "$PULL_ONLY" == false ]] && ! command -v ollama >/dev/null; then
  echo "==> Installing Ollama (requires curl + sudo)…"
  if ! curl -fsSL https://ollama.com/install.sh | sh; then
    echo "System install failed — falling back to user-local under workspace/.local-run/ollama"
    install_user_local
  fi
fi

if [[ "$USER_LOCAL" == true ]] || [[ -x "${OLLAMA_DIR}/bin/ollama" ]]; then
  OLLAMA_BIN="${OLLAMA_DIR}/bin/ollama"
  export PATH="${OLLAMA_DIR}/bin:${PATH}"
fi

if ! command -v ollama >/dev/null && [[ ! -x "$OLLAMA_BIN" ]]; then
  echo "ollama not on PATH — install manually: https://ollama.com/download" >&2
  exit 1
fi

if systemctl is-active --quiet ollama 2>/dev/null || pgrep -x ollama >/dev/null; then
  echo "Ollama already running"
else
  echo "==> Starting ollama serve (background)…"
  mkdir -p "${ROOT}/workspace/.local-run"
  nohup "$OLLAMA_BIN" serve >"${ROOT}/workspace/.local-run/ollama.log" 2>&1 &
  sleep 3
fi

echo "==> Pulling model ${MODEL} (tier ${RAM_TIER}, gpu ${GPU_MODE})…"
"$OLLAMA_BIN" pull "$MODEL"

echo "==> Smoke test (API)"
curl -sf "${OFDD_OLLAMA_BASE_URL:-http://127.0.0.1:11434}/api/tags" | python3 -m json.tool | head -20 || true

echo ""
echo "OK — Ollama ready. Restart bridge:"
echo "  ./scripts/run_local.sh start"
echo "  AI Agent tab → local chat uses Ollama (${MODEL})"
