#!/usr/bin/env bash
# Bootstrap a fresh Rust Open-FDD edge host from GHCR (no source checkout required on device).
#
#   curl -fsSL https://github.com/bbartling/open-fdd/raw/refs/heads/master/scripts/openfdd_rust_edge_bootstrap.sh -o /tmp/openfdd_rust_edge_bootstrap.sh
#   bash /tmp/openfdd_rust_edge_bootstrap.sh --start
set -euo pipefail

OPENFDD_ROOT="${OPENFDD_ROOT:-$HOME/open-fdd}"
OPENFDD_REPO_REF="${OPENFDD_REPO_REF:-master}"
OPENFDD_IMAGE_TAG="${OPENFDD_IMAGE_TAG:-nightly}"
GITHUB_REPO="bbartling/open-fdd"
DO_START=false
FORCE_AUTH=false
DO_RESTART=false
SHOW_SECRETS=false
DRY_RUN=false
COMPOSE_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --start) DO_START=true; shift ;;
    --image-tag) OPENFDD_IMAGE_TAG="$2"; shift 2 ;;
    --platform) OPENFDD_DOCKER_PLATFORM="$2"; shift 2 ;;
    --repo-ref) OPENFDD_REPO_REF="$2"; shift 2 ;;
    --root) OPENFDD_ROOT="$2"; shift 2 ;;
    --force-auth) FORCE_AUTH=true; shift ;;
    --restart) DO_RESTART=true; shift ;;
    --show-secrets) SHOW_SECRETS=true; shift ;;
    --compose-url) COMPOSE_URL="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help)
      grep '^#' "$0" | head -20 | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

mkdir -p "$OPENFDD_ROOT/scripts"
LIB="$OPENFDD_ROOT/scripts/openfdd_rust_site_lib.sh"
if [[ ! -f "$LIB" ]]; then
  curl -fsSL -o "$LIB" "https://github.com/${GITHUB_REPO}/raw/refs/heads/${OPENFDD_REPO_REF}/scripts/openfdd_rust_site_lib.sh" \
    || cp "$(dirname "$0")/openfdd_rust_site_lib.sh" "$LIB" 2>/dev/null || true
fi
# shellcheck source=scripts/openfdd_rust_site_lib.sh
source "$LIB"

PLATFORM="$(openfdd_rust_export_docker_platform)"
export OPENFDD_IMAGE_TAG OPENFDD_ROOT

echo "==> Rust edge bootstrap root=$OPENFDD_ROOT platform=$PLATFORM tag=$OPENFDD_IMAGE_TAG"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "DRY_RUN: would create layout, auth, compose, optional start"
  exit 0
fi

openfdd_rust_check_docker

mkdir -p "$OPENFDD_ROOT/workspace"/{auth,logs,reports/generated,data/drivers,data/historian,data/rules,data/model,backups,bacnet/commissioning}
openfdd_rust_ensure_container_workspace "$OPENFDD_ROOT"

for script in openfdd_auth_lib.sh openfdd_rust_site_backup.sh openfdd_rust_site_update.sh openfdd_rust_check_ghcr_platform.sh openfdd_rust_edge_validate.sh; do
  dest="$OPENFDD_ROOT/scripts/$script"
  if [[ ! -x "$dest" ]]; then
    openfdd_rust_github_raw "$OPENFDD_REPO_REF" "scripts/$script" "$dest" 2>/dev/null \
      || cp "$(dirname "$0")/$script" "$dest" 2>/dev/null || true
    chmod +x "$dest" 2>/dev/null || true
  fi
done

AUTH_PATH="$OPENFDD_ROOT/workspace/auth.env.local"
openfdd_rust_generate_auth_env_local "$AUTH_PATH" "$FORCE_AUTH" "$SHOW_SECRETS"

if [[ ! -f "$OPENFDD_ROOT/workspace/data.env.local" ]]; then
  cat >"$OPENFDD_ROOT/workspace/data.env.local" <<'EOF'
# Site data paths — generated by rust bootstrap
OPENFDD_WORKSPACE=/var/openfdd/workspace
OPENFDD_BACNET_MODE=live
OPENFDD_MODBUS_MODE=live
EOF
fi

if [[ ! -f "$OPENFDD_ROOT/workspace/bacnet/commissioning/commission.env" ]]; then
  cat >"$OPENFDD_ROOT/workspace/bacnet/commissioning/commission.env" <<'EOF'
# BACnet commissioning defaults — edit for live OT LAN
OPENFDD_BACNET_IFACE=<replace-with-iface>
OPENFDD_BACNET_BIND=<replace-with-ip>/24:47808
OPENFDD_BACNET_ROUTER_IP=<replace-with-router-ip>
OPENFDD_BACNET_MSTP_NET=2000
OPENFDD_BENCH_DEVICE_INSTANCE=<replace-with-device-instance>
EOF
fi

COMPOSE_DEST="$OPENFDD_ROOT/docker-compose.yml"
if [[ -n "$COMPOSE_URL" ]]; then
  curl -fsSL -o "$COMPOSE_DEST" "$COMPOSE_URL"
else
  openfdd_rust_install_edge_compose "$OPENFDD_ROOT" "$OPENFDD_REPO_REF"
fi
openfdd_rust_write_site_env "$OPENFDD_ROOT" "$OPENFDD_IMAGE_TAG"

LAN_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1); exit}' || true)"
if [[ -n "$LAN_IP" ]]; then
  echo "Suggested BACnet bind: ${LAN_IP}/24:47808 (edit workspace/bacnet/commissioning/commission.env for live OT)"
fi

if [[ "$DO_START" == "true" || "$DO_RESTART" == "true" ]]; then
  export OPENFDD_IMAGE_TAG
  cd "$OPENFDD_ROOT"
  "$OPENFDD_ROOT/scripts/openfdd_rust_check_ghcr_platform.sh" || echo "WARN: GHCR check failed — try local build or publish workflow"
  docker compose pull || true
  if [[ "$DO_RESTART" == "true" ]]; then
    docker compose up -d --force-recreate
  else
    docker compose up -d
  fi
  openfdd_rust_wait_for_health "http://127.0.0.1:8080/api/health" 120
  openfdd_rust_login_smoke "http://127.0.0.1:8080" "$AUTH_PATH"
  echo "Bootstrap start OK — open http://127.0.0.1:8080"
fi

echo "Bootstrap layout OK: $OPENFDD_ROOT"
echo "Next: cd $OPENFDD_ROOT && docker compose up -d   # or re-run with --start"
