#!/usr/bin/env bash
# Bench 5007 long FDD validation — default 2h, overnight 12h, synthetic for CI.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export OPENFDD_BASE_URL="${OPENFDD_BASE_URL:-http://127.0.0.1:8765}"
export OPENFDD_AUTH_ENV="${OPENFDD_AUTH_ENV:-workspace/auth.env.local}"
export OPENFDD_SMOKE_SITE_ID="${OPENFDD_SMOKE_SITE_ID:-demo}"
export OPENFDD_SMOKE_BACNET_DEVICE_ID="${OPENFDD_SMOKE_BACNET_DEVICE_ID:-5007}"
export OPENFDD_SMOKE_NIAGARA_STATION="${OPENFDD_SMOKE_NIAGARA_STATION:-bench9065}"
export OPENFDD_SMOKE_POLL_SECONDS="${OPENFDD_SMOKE_POLL_SECONDS:-60}"
export OPENFDD_SMOKE_BASELINE_MINUTES="${OPENFDD_SMOKE_BASELINE_MINUTES:-20}"
export OPENFDD_SMOKE_CONFIRMATION_MINUTES="${OPENFDD_SMOKE_CONFIRMATION_MINUTES:-10}"
export OPENFDD_SMOKE_CONFIRMATION_ROWS="${OPENFDD_SMOKE_CONFIRMATION_ROWS:-10}"
export OPENFDD_SMOKE_PRIMARY_SEMANTIC="${OPENFDD_SMOKE_PRIMARY_SEMANTIC:-duct-t}"
export OPENFDD_SMOKE_FORCED_THRESHOLD_F="${OPENFDD_SMOKE_FORCED_THRESHOLD_F:-80.0}"

if [[ "${OPENFDD_SMOKE_OVERNIGHT:-false}" == "true" ]]; then
  export OPENFDD_SMOKE_DURATION_MINUTES="${OPENFDD_SMOKE_DURATION_MINUTES:-720}"
else
  export OPENFDD_SMOKE_DURATION_MINUTES="${OPENFDD_SMOKE_DURATION_MINUTES:-120}"
fi

PYTHON="${ROOT}/.venv/bin/python"
if [[ ! -x "$PYTHON" ]]; then
  PYTHON=python3
fi

echo "==> Bench 5007 long FDD smoke (${OPENFDD_SMOKE_DURATION_MINUTES} min, confirmation window=${OPENFDD_SMOKE_CONFIRMATION_ROWS} rows)"
exec "$PYTHON" scripts/smoke_bench_5007_long_fdd.py "$@"
