# GitHub Pages / local: bundle install && bundle exec jekyll build -s docs -d _site
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-seo-tag"
